// Generated by view binder compiler. Do not edit!
package com.example.myfirstapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.myfirstapp.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityProductListBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final RecyclerView Products;

  @NonNull
  public final TextView Shopname;

  @NonNull
  public final Button prodListBackhome;

  @NonNull
  public final Button prodListBacktoshops;

  @NonNull
  public final TextView textView3;

  private ActivityProductListBinding(@NonNull ConstraintLayout rootView,
      @NonNull RecyclerView Products, @NonNull TextView Shopname, @NonNull Button prodListBackhome,
      @NonNull Button prodListBacktoshops, @NonNull TextView textView3) {
    this.rootView = rootView;
    this.Products = Products;
    this.Shopname = Shopname;
    this.prodListBackhome = prodListBackhome;
    this.prodListBacktoshops = prodListBacktoshops;
    this.textView3 = textView3;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityProductListBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityProductListBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_product_list, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityProductListBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.Products;
      RecyclerView Products = ViewBindings.findChildViewById(rootView, id);
      if (Products == null) {
        break missingId;
      }

      id = R.id.Shopname;
      TextView Shopname = ViewBindings.findChildViewById(rootView, id);
      if (Shopname == null) {
        break missingId;
      }

      id = R.id.prod_list_backhome;
      Button prodListBackhome = ViewBindings.findChildViewById(rootView, id);
      if (prodListBackhome == null) {
        break missingId;
      }

      id = R.id.prod_list_backtoshops;
      Button prodListBacktoshops = ViewBindings.findChildViewById(rootView, id);
      if (prodListBacktoshops == null) {
        break missingId;
      }

      id = R.id.textView3;
      TextView textView3 = ViewBindings.findChildViewById(rootView, id);
      if (textView3 == null) {
        break missingId;
      }

      return new ActivityProductListBinding((ConstraintLayout) rootView, Products, Shopname,
          prodListBackhome, prodListBacktoshops, textView3);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
