// Generated by view binder compiler. Do not edit!
package com.example.myfirstapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.Spinner;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.myfirstapp.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityCartItemconfigureBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final TextView configProductname;

  @NonNull
  public final TextView configQuantity;

  @NonNull
  public final TextView configUnitprice;

  @NonNull
  public final Button confirmingDeletion;

  @NonNull
  public final Button itemconfigBacktoCart;

  @NonNull
  public final Spinner quantityconfigSpinner;

  @NonNull
  public final TextView textView14;

  @NonNull
  public final TextView textView18;

  @NonNull
  public final TextView textView20;

  @NonNull
  public final TextView textView21;

  @NonNull
  public final TextView textView24;

  @NonNull
  public final Button updateQuantity;

  private ActivityCartItemconfigureBinding(@NonNull ConstraintLayout rootView,
      @NonNull TextView configProductname, @NonNull TextView configQuantity,
      @NonNull TextView configUnitprice, @NonNull Button confirmingDeletion,
      @NonNull Button itemconfigBacktoCart, @NonNull Spinner quantityconfigSpinner,
      @NonNull TextView textView14, @NonNull TextView textView18, @NonNull TextView textView20,
      @NonNull TextView textView21, @NonNull TextView textView24, @NonNull Button updateQuantity) {
    this.rootView = rootView;
    this.configProductname = configProductname;
    this.configQuantity = configQuantity;
    this.configUnitprice = configUnitprice;
    this.confirmingDeletion = confirmingDeletion;
    this.itemconfigBacktoCart = itemconfigBacktoCart;
    this.quantityconfigSpinner = quantityconfigSpinner;
    this.textView14 = textView14;
    this.textView18 = textView18;
    this.textView20 = textView20;
    this.textView21 = textView21;
    this.textView24 = textView24;
    this.updateQuantity = updateQuantity;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityCartItemconfigureBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityCartItemconfigureBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_cart_itemconfigure, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityCartItemconfigureBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.config_productname;
      TextView configProductname = ViewBindings.findChildViewById(rootView, id);
      if (configProductname == null) {
        break missingId;
      }

      id = R.id.config_quantity;
      TextView configQuantity = ViewBindings.findChildViewById(rootView, id);
      if (configQuantity == null) {
        break missingId;
      }

      id = R.id.config_unitprice;
      TextView configUnitprice = ViewBindings.findChildViewById(rootView, id);
      if (configUnitprice == null) {
        break missingId;
      }

      id = R.id.confirming_deletion;
      Button confirmingDeletion = ViewBindings.findChildViewById(rootView, id);
      if (confirmingDeletion == null) {
        break missingId;
      }

      id = R.id.itemconfig_backto_cart;
      Button itemconfigBacktoCart = ViewBindings.findChildViewById(rootView, id);
      if (itemconfigBacktoCart == null) {
        break missingId;
      }

      id = R.id.quantityconfig_spinner;
      Spinner quantityconfigSpinner = ViewBindings.findChildViewById(rootView, id);
      if (quantityconfigSpinner == null) {
        break missingId;
      }

      id = R.id.textView14;
      TextView textView14 = ViewBindings.findChildViewById(rootView, id);
      if (textView14 == null) {
        break missingId;
      }

      id = R.id.textView18;
      TextView textView18 = ViewBindings.findChildViewById(rootView, id);
      if (textView18 == null) {
        break missingId;
      }

      id = R.id.textView20;
      TextView textView20 = ViewBindings.findChildViewById(rootView, id);
      if (textView20 == null) {
        break missingId;
      }

      id = R.id.textView21;
      TextView textView21 = ViewBindings.findChildViewById(rootView, id);
      if (textView21 == null) {
        break missingId;
      }

      id = R.id.textView24;
      TextView textView24 = ViewBindings.findChildViewById(rootView, id);
      if (textView24 == null) {
        break missingId;
      }

      id = R.id.update_quantity;
      Button updateQuantity = ViewBindings.findChildViewById(rootView, id);
      if (updateQuantity == null) {
        break missingId;
      }

      return new ActivityCartItemconfigureBinding((ConstraintLayout) rootView, configProductname,
          configQuantity, configUnitprice, confirmingDeletion, itemconfigBacktoCart,
          quantityconfigSpinner, textView14, textView18, textView20, textView21, textView24,
          updateQuantity);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
