// Generated by view binder compiler. Do not edit!
package com.example.myfirstapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.myfirstapp.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityCustomerHomeBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final TextView banner;

  @NonNull
  public final Button gocart;

  @NonNull
  public final Button goshop;

  @NonNull
  public final Button logout;

  @NonNull
  public final Button pastOrder;

  private ActivityCustomerHomeBinding(@NonNull ConstraintLayout rootView, @NonNull TextView banner,
      @NonNull Button gocart, @NonNull Button goshop, @NonNull Button logout,
      @NonNull Button pastOrder) {
    this.rootView = rootView;
    this.banner = banner;
    this.gocart = gocart;
    this.goshop = goshop;
    this.logout = logout;
    this.pastOrder = pastOrder;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityCustomerHomeBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityCustomerHomeBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_customer_home, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityCustomerHomeBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.banner;
      TextView banner = ViewBindings.findChildViewById(rootView, id);
      if (banner == null) {
        break missingId;
      }

      id = R.id.gocart;
      Button gocart = ViewBindings.findChildViewById(rootView, id);
      if (gocart == null) {
        break missingId;
      }

      id = R.id.goshop;
      Button goshop = ViewBindings.findChildViewById(rootView, id);
      if (goshop == null) {
        break missingId;
      }

      id = R.id.logout;
      Button logout = ViewBindings.findChildViewById(rootView, id);
      if (logout == null) {
        break missingId;
      }

      id = R.id.past_order;
      Button pastOrder = ViewBindings.findChildViewById(rootView, id);
      if (pastOrder == null) {
        break missingId;
      }

      return new ActivityCustomerHomeBinding((ConstraintLayout) rootView, banner, gocart, goshop,
          logout, pastOrder);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
