// Generated by view binder compiler. Do not edit!
package com.example.myfirstapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.Spinner;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.myfirstapp.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityProductDetailsBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final TextView BrandName;

  @NonNull
  public final TextView PriceNum;

  @NonNull
  public final TextView ProductName;

  @NonNull
  public final TextView WeightNum;

  @NonNull
  public final Button addToCart;

  @NonNull
  public final Button prodDetailToProdlist;

  @NonNull
  public final Button prodDetailToShoplist;

  @NonNull
  public final ConstraintLayout productName;

  @NonNull
  public final Spinner productnumSpinner;

  @NonNull
  public final TextView textView10;

  @NonNull
  public final TextView textView11;

  @NonNull
  public final TextView textView13;

  @NonNull
  public final TextView textView17;

  @NonNull
  public final TextView textView8;

  @NonNull
  public final TextView textView9;

  private ActivityProductDetailsBinding(@NonNull ConstraintLayout rootView,
      @NonNull TextView BrandName, @NonNull TextView PriceNum, @NonNull TextView ProductName,
      @NonNull TextView WeightNum, @NonNull Button addToCart, @NonNull Button prodDetailToProdlist,
      @NonNull Button prodDetailToShoplist, @NonNull ConstraintLayout productName,
      @NonNull Spinner productnumSpinner, @NonNull TextView textView10,
      @NonNull TextView textView11, @NonNull TextView textView13, @NonNull TextView textView17,
      @NonNull TextView textView8, @NonNull TextView textView9) {
    this.rootView = rootView;
    this.BrandName = BrandName;
    this.PriceNum = PriceNum;
    this.ProductName = ProductName;
    this.WeightNum = WeightNum;
    this.addToCart = addToCart;
    this.prodDetailToProdlist = prodDetailToProdlist;
    this.prodDetailToShoplist = prodDetailToShoplist;
    this.productName = productName;
    this.productnumSpinner = productnumSpinner;
    this.textView10 = textView10;
    this.textView11 = textView11;
    this.textView13 = textView13;
    this.textView17 = textView17;
    this.textView8 = textView8;
    this.textView9 = textView9;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityProductDetailsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityProductDetailsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_product_details, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityProductDetailsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.Brand_Name;
      TextView BrandName = ViewBindings.findChildViewById(rootView, id);
      if (BrandName == null) {
        break missingId;
      }

      id = R.id.Price_Num;
      TextView PriceNum = ViewBindings.findChildViewById(rootView, id);
      if (PriceNum == null) {
        break missingId;
      }

      id = R.id.Product_Name;
      TextView ProductName = ViewBindings.findChildViewById(rootView, id);
      if (ProductName == null) {
        break missingId;
      }

      id = R.id.Weight_Num;
      TextView WeightNum = ViewBindings.findChildViewById(rootView, id);
      if (WeightNum == null) {
        break missingId;
      }

      id = R.id.add_to_cart;
      Button addToCart = ViewBindings.findChildViewById(rootView, id);
      if (addToCart == null) {
        break missingId;
      }

      id = R.id.prod_detail_to_prodlist;
      Button prodDetailToProdlist = ViewBindings.findChildViewById(rootView, id);
      if (prodDetailToProdlist == null) {
        break missingId;
      }

      id = R.id.prod_detail_to_shoplist;
      Button prodDetailToShoplist = ViewBindings.findChildViewById(rootView, id);
      if (prodDetailToShoplist == null) {
        break missingId;
      }

      ConstraintLayout productName = (ConstraintLayout) rootView;

      id = R.id.productnum_spinner;
      Spinner productnumSpinner = ViewBindings.findChildViewById(rootView, id);
      if (productnumSpinner == null) {
        break missingId;
      }

      id = R.id.textView10;
      TextView textView10 = ViewBindings.findChildViewById(rootView, id);
      if (textView10 == null) {
        break missingId;
      }

      id = R.id.textView11;
      TextView textView11 = ViewBindings.findChildViewById(rootView, id);
      if (textView11 == null) {
        break missingId;
      }

      id = R.id.textView13;
      TextView textView13 = ViewBindings.findChildViewById(rootView, id);
      if (textView13 == null) {
        break missingId;
      }

      id = R.id.textView17;
      TextView textView17 = ViewBindings.findChildViewById(rootView, id);
      if (textView17 == null) {
        break missingId;
      }

      id = R.id.textView8;
      TextView textView8 = ViewBindings.findChildViewById(rootView, id);
      if (textView8 == null) {
        break missingId;
      }

      id = R.id.textView9;
      TextView textView9 = ViewBindings.findChildViewById(rootView, id);
      if (textView9 == null) {
        break missingId;
      }

      return new ActivityProductDetailsBinding((ConstraintLayout) rootView, BrandName, PriceNum,
          ProductName, WeightNum, addToCart, prodDetailToProdlist, prodDetailToShoplist,
          productName, productnumSpinner, textView10, textView11, textView13, textView17, textView8,
          textView9);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
