// Generated by view binder compiler. Do not edit!
package com.example.myfirstapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.myfirstapp.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityCheckoutBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final RecyclerView cartItemlist;

  @NonNull
  public final TextView cartNetcost;

  @NonNull
  public final View divider2;

  @NonNull
  public final View divider3;

  @NonNull
  public final Button finishorder;

  @NonNull
  public final Button ordertohome;

  @NonNull
  public final TextView textView12;

  @NonNull
  public final TextView textView22;

  @NonNull
  public final TextView textView6;

  private ActivityCheckoutBinding(@NonNull ConstraintLayout rootView,
      @NonNull RecyclerView cartItemlist, @NonNull TextView cartNetcost, @NonNull View divider2,
      @NonNull View divider3, @NonNull Button finishorder, @NonNull Button ordertohome,
      @NonNull TextView textView12, @NonNull TextView textView22, @NonNull TextView textView6) {
    this.rootView = rootView;
    this.cartItemlist = cartItemlist;
    this.cartNetcost = cartNetcost;
    this.divider2 = divider2;
    this.divider3 = divider3;
    this.finishorder = finishorder;
    this.ordertohome = ordertohome;
    this.textView12 = textView12;
    this.textView22 = textView22;
    this.textView6 = textView6;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityCheckoutBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityCheckoutBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_checkout, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityCheckoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.cart_itemlist;
      RecyclerView cartItemlist = ViewBindings.findChildViewById(rootView, id);
      if (cartItemlist == null) {
        break missingId;
      }

      id = R.id.cart_netcost;
      TextView cartNetcost = ViewBindings.findChildViewById(rootView, id);
      if (cartNetcost == null) {
        break missingId;
      }

      id = R.id.divider2;
      View divider2 = ViewBindings.findChildViewById(rootView, id);
      if (divider2 == null) {
        break missingId;
      }

      id = R.id.divider3;
      View divider3 = ViewBindings.findChildViewById(rootView, id);
      if (divider3 == null) {
        break missingId;
      }

      id = R.id.finishorder;
      Button finishorder = ViewBindings.findChildViewById(rootView, id);
      if (finishorder == null) {
        break missingId;
      }

      id = R.id.ordertohome;
      Button ordertohome = ViewBindings.findChildViewById(rootView, id);
      if (ordertohome == null) {
        break missingId;
      }

      id = R.id.textView12;
      TextView textView12 = ViewBindings.findChildViewById(rootView, id);
      if (textView12 == null) {
        break missingId;
      }

      id = R.id.textView22;
      TextView textView22 = ViewBindings.findChildViewById(rootView, id);
      if (textView22 == null) {
        break missingId;
      }

      id = R.id.textView6;
      TextView textView6 = ViewBindings.findChildViewById(rootView, id);
      if (textView6 == null) {
        break missingId;
      }

      return new ActivityCheckoutBinding((ConstraintLayout) rootView, cartItemlist, cartNetcost,
          divider2, divider3, finishorder, ordertohome, textView12, textView22, textView6);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
