// Generated by view binder compiler. Do not edit!
package com.example.myfirstapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.myfirstapp.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityOrderhistoryDetailsBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button detailUptoorderhist;

  @NonNull
  public final View divider4;

  @NonNull
  public final TextView histDetailsStatus;

  @NonNull
  public final RecyclerView orderhistProdlist;

  @NonNull
  public final TextView textView26;

  @NonNull
  public final TextView textView27;

  @NonNull
  public final TextView textView28;

  @NonNull
  public final TextView textView30;

  private ActivityOrderhistoryDetailsBinding(@NonNull ConstraintLayout rootView,
      @NonNull Button detailUptoorderhist, @NonNull View divider4,
      @NonNull TextView histDetailsStatus, @NonNull RecyclerView orderhistProdlist,
      @NonNull TextView textView26, @NonNull TextView textView27, @NonNull TextView textView28,
      @NonNull TextView textView30) {
    this.rootView = rootView;
    this.detailUptoorderhist = detailUptoorderhist;
    this.divider4 = divider4;
    this.histDetailsStatus = histDetailsStatus;
    this.orderhistProdlist = orderhistProdlist;
    this.textView26 = textView26;
    this.textView27 = textView27;
    this.textView28 = textView28;
    this.textView30 = textView30;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityOrderhistoryDetailsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityOrderhistoryDetailsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_orderhistory_details, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityOrderhistoryDetailsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.detail_uptoorderhist;
      Button detailUptoorderhist = ViewBindings.findChildViewById(rootView, id);
      if (detailUptoorderhist == null) {
        break missingId;
      }

      id = R.id.divider4;
      View divider4 = ViewBindings.findChildViewById(rootView, id);
      if (divider4 == null) {
        break missingId;
      }

      id = R.id.hist_details_status;
      TextView histDetailsStatus = ViewBindings.findChildViewById(rootView, id);
      if (histDetailsStatus == null) {
        break missingId;
      }

      id = R.id.orderhist_prodlist;
      RecyclerView orderhistProdlist = ViewBindings.findChildViewById(rootView, id);
      if (orderhistProdlist == null) {
        break missingId;
      }

      id = R.id.textView26;
      TextView textView26 = ViewBindings.findChildViewById(rootView, id);
      if (textView26 == null) {
        break missingId;
      }

      id = R.id.textView27;
      TextView textView27 = ViewBindings.findChildViewById(rootView, id);
      if (textView27 == null) {
        break missingId;
      }

      id = R.id.textView28;
      TextView textView28 = ViewBindings.findChildViewById(rootView, id);
      if (textView28 == null) {
        break missingId;
      }

      id = R.id.textView30;
      TextView textView30 = ViewBindings.findChildViewById(rootView, id);
      if (textView30 == null) {
        break missingId;
      }

      return new ActivityOrderhistoryDetailsBinding((ConstraintLayout) rootView,
          detailUptoorderhist, divider4, histDetailsStatus, orderhistProdlist, textView26,
          textView27, textView28, textView30);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
